services:
  go2rtc:
    image: alexxit/go2rtc:latest
    restart: unless-stopped
    privileged: true
    environment:
      TZ: ${TZ:-Europe/Copenhagen}
    volumes:
      - ./go2rtc:/config
    network_mode: host

  camera-streamer:
    image: camera-streamer-builder
    pull_policy: never
    restart: unless-stopped
    depends_on:
      - go2rtc
    environment:
      TZ: ${TZ:-Europe/Copenhagen}
    volumes:
      - ./bin:/app
    command: /bin/bash -c /app/camera-streamer
    network_mode: host
